#!/usr/bin/env bash
set -e

# This allows us to use the same template
# for development, staging and production.
CONFIG_PATH="/etc/nginx/conf.d/default.conf"
STAGING_IP=$(curl 169.254.169.254/latest/meta-data/public-ipv4/)
STAGING_HOSTNAME="staging"
DOMAIN_NAME="productionexample.com"
HOSTNAME="staging"

#if [[ $(hostname) != "${STAGING_HOSTNAME}" ]]; then
#  sed -i "s/${STAGING_IP}/${DOMAIN_NAME}/g" "${CONFIG_PATH}"
#fi

if [[ $HOSTNAME = ${STAGING_HOSTNAME} ]]; then
  sed -ri "s/(\b[0-9]{1,3}\.){3}[0-9]{1,3}\b/${STAGING_IP}/g" "${CONFIG_PATH}"
fi

#
# Execute the CMD from the Dockerfile.
exec "$@"
